# Used by make docker-test-and-zbuild-all. See BUILDING.md

FROM rust:latest as build

RUN apt-get update
RUN apt-get full-upgrade -y
RUN apt-get install -y zip
RUN cargo install -f cross

WORKDIR /abc
COPY . .

# RUN make test
RUN make build-all

# Now copy it into our base image.
FROM scratch AS export
COPY --from=build /abc/bin/* .